In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import scipy.stats as stats
import datetime

In [89]:
df = pd.ExcelFile("..\..\Local\landfilllmopdata.xlsx")
county_list = pd.read_excel("..\Public Data\VARIABLE for coder X.xlsx")
df.sheet_names

['Summary', 'LMOP Database', 'Field Descriptions']

In [90]:
df = pd.read_excel("..\..\Local\landfilllmopdata.xlsx", sheet_name="LMOP Database")
df

,GHGRP ID,Landfill ID,Landfill Name,State,Landfill Alias,Physical Address,City,County,Zip Code,Latitude,...,LFG Generated (mmscfd),LFG Collection System In Place?,LFG Collected (mmscfd),LFG Collected Year,Percent Methane,Flares in Place?,Number of Flares,LFG Flared (mmscfd),LFG Flared Year,Gas Collection System Comments
0,1007341.0,1994,Anchorage Regional Landfill,AK,NaN,15500 E. Eagle River Loop Road,Eagle River,Anchorage,99577,61.293281,...,5.675,Yes,4.026,2021.0,51.2,Yes,1.0,1.910,2021.0,4/10-GCCS in operation since Oct. 2006.; 2010-...
1,1010389.0,11941,Capitol Disposal Landfill,AK,NaN,5600 Tonsgard Court,Juneau,Juneau,99801,58.352800,...,0.765,Yes,0.661,2021.0,26.5,Yes,1.0,0.661,2021.0,"9/10-16 wells over 13 acres, system installed ..."
2,1005349.0,12216,Central Peninsula Landfill (CPL),AK,Soldotna Landfill; Central Peninsula Baling Fa...,46915 Sterling Highway,Soldotna,Kenai Peninsula,99669,60.443004,...,0.657,No,NaN,NaN,NaN,No,NaN,NaN,NaN,2010-Passive venting.
3,NaN,10960,Kodiak Island Borough Landfill,AK,NaN,1203 Monashka Bay Road,Kodiak,Kodiak Island,99615,57.808740,...,NaN,No,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
4,1004380.0,11020,Merrill Field Landfill,AK,NaN,800 Merrill Field Drive,Anchorage,Anchorage,99501,61.212660,...,1.187,Yes,0.126,2021.0,33.2,Yes,1.0,0.126,2021.0,"2012-30 wells, system capacity=500 acfm."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2631,1011229.0,20722,Campbell County Landfill No.2,WY,NaN,4 North Landfill Road,Gillette,Campbell,82716,44.392560,...,0.325,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN
2632,1005225.0,11100,Casper Balefill,WY,City of Casper Regional Solid Waste Facility,1886 N. Station Road,Evansville,Natrona,82636,42.873192,...,0.585,Yes,0.287,2021.0,29.2,Yes,NaN,0.287,2021.0,2012-Passive vents/flares only.
2633,1005583.0,2196,Cheyenne Landfill,WY,NaN,1461 Happy Jack Road,Cheyenne,Laramie,82009,41.135000,...,0.885,No,NaN,NaN,NaN,No,NaN,NaN,NaN,2012-Passive vents/flares only.
2634,1013159.0,21136,Eastern Laramie County SWDD,WY,NaN,4990 CR 216,Burns,Laramie,82053,41.230852,...,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN
2635,NaN,11140,Sheridan Existing Landfill,WY,NaN,83 East Ridge Road,Sheridan,Sheridan,82801,44.804335,...,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,1/09-Passive vents just installed.

In [91]:
np.sum(df.isna())

GHGRP ID                                        1308
Landfill ID                                        0
Landfill Name                                      0
State                                              0
Landfill Alias                                  1756
Physical Address                                 468
City                                             178
County                                             5
Zip Code                                         359
Latitude                                         330
Longitude                                        330
Composting?                                        0
Ownership Type                                     0
Landfill Owner Organization(s)                   148
Landfill Operator Organization                   613
Year Landfill Opened                             380
Landfill Closure Year                            284
Current Landfill Status                            0
Design Landfill Area (acres)                    1416
Current Landfill Area (acres)                   1239
Design Landfill Depth (feet)                    2100
Current Landfill Depth (feet)                   2127
Landfill Design Capacity (tons)                 1295
Waste in Place (tons)                            460
Waste in Place Year                             1179
Annual Waste Acceptance Rate (tons per year)     400
Annual Waste Acceptance Year                     929
Does LF Recirculate Leachate?                      0
Leachate Recirc Frequency (Past 10 Yrs)            1
Permitted as RD&D LF?                              0
LFG Generated (mmscfd)                          1496
LFG Collection System In Place?                    0
LFG Collected (mmscfd)                          1500
LFG Collected Year                              1605
Percent Methane                                 1472
Flares in Place?                                   0
Number of Flares                                1940
LFG Flared (mmscfd)                             1640
LFG Flared Year                                 1706
Gas Collection System Comments                  1436
dtype: int64

In [92]:
df[df["Year Landfill Opened"].isna()]

,GHGRP ID,Landfill ID,Landfill Name,State,Landfill Alias,Physical Address,City,County,Zip Code,Latitude,...,LFG Generated (mmscfd),LFG Collection System In Place?,LFG Collected (mmscfd),LFG Collected Year,Percent Methane,Flares in Place?,Number of Flares,LFG Flared (mmscfd),LFG Flared Year,Gas Collection System Comments
3,NaN,10960,Kodiak Island Borough Landfill,AK,NaN,1203 Monashka Bay Road,Kodiak,Kodiak Island,99615,57.808740,...,NaN,No,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
17,NaN,2409,Chilton County Landfill,AL,NaN,300 Industrial Drive,Thorsby,Chilton,35171,32.928500,...,NaN,No,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
49,NaN,2015,Walker County Landfill (Carbon Hill),AL,NaN,NaN,Jasper,Walker,NaN,33.875000,...,NaN,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN
51,NaN,11542,Ashley County Landfill,AR,NaN,309 Ashley 438 Road,Hamburg,Ashley,71646,33.212000,...,NaN,Unknown,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
55,NaN,11547,City of Helena - West Helena Regional LF,AR,NaN,1448 B Phillips Highway 217,West Helena,Phillips,72390,34.567260,...,NaN,Unknown,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2567,NaN,21142,Highway G Sanitary LF,WI,NaN,7001 CR G,Eagle River,Vilas,54521,45.968199,...,NaN,Unknown,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
2605,NaN,21143,Vernon County Solid Waste/Recycling Facility,WI,NaN,S3705 County Road,Viroqua,Vernon,54665,43.597910,...,NaN,Unknown,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
2620,NaN,2222,Nicholas County Solid Waste Authority LF,WV,NaN,Route 55,Calvin,Nicholas,26660,38.338500,...,NaN,No,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
2622,NaN,2223,Philip Gwinn Landfill,WV,NaN,NaN,Bluefield,Mercer,24701,NaN,...,NaN,No,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN
2629,NaN,21067,Webster County Landfill,WV,NaN,Excelsior Pleasant Ridge Road,Webster Springs,Webster,NaN,38.443134,...,NaN,Unknown,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN

In [93]:
landfill_sites_1990 = df[df["Year Landfill Opened"]<=1990]

In [94]:
states = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming',
    "GU": 'Guam',
    'PR': 'Puerto Rico',
    'VI': 'Virgin Islands'
}

In [95]:
landfill_sites_1990["STATE"]=landfill_sites_1990["State"].apply(lambda x: states[x])

C:\Users\longy\AppData\Local\Temp/ipykernel_2692/824562517.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  landfill_sites_1990["STATE"]=landfill_sites_1990["State"].apply(lambda x: states[x])

In [96]:
def county_name_transformer(x:str,dropped_words):
    # This function converts county name to a "cleaner" form by 1)converting all chars to lower 2)remove the words given by dropped_words 3)remove some special symbols (".","'"). 
    # Eg. if dropped_words = ["county"], DuPage -> dupage, DuPage County -> dupage.  
    x=x.strip()
    x=x.split(" ")
    x=[str.lower(i) for i in x if str.lower(i) not in dropped_words]
    x=[str.replace(i,".","") for i in x]
    x=[str.replace(i,"'","") for i in x]
    x="".join(x)
    return x

In [97]:
landfill_sites_1990

,GHGRP ID,Landfill ID,Landfill Name,State,Landfill Alias,Physical Address,City,County,Zip Code,Latitude,...,LFG Collection System In Place?,LFG Collected (mmscfd),LFG Collected Year,Percent Methane,Flares in Place?,Number of Flares,LFG Flared (mmscfd),LFG Flared Year,Gas Collection System Comments,STATE
0,1007341.0,1994,Anchorage Regional Landfill,AK,NaN,15500 E. Eagle River Loop Road,Eagle River,Anchorage,99577,61.293281,...,Yes,4.026,2021.0,51.2,Yes,1.0,1.910,2021.0,4/10-GCCS in operation since Oct. 2006.; 2010-...,Alaska
1,1010389.0,11941,Capitol Disposal Landfill,AK,NaN,5600 Tonsgard Court,Juneau,Juneau,99801,58.352800,...,Yes,0.661,2021.0,26.5,Yes,1.0,0.661,2021.0,"9/10-16 wells over 13 acres, system installed ...",Alaska
2,1005349.0,12216,Central Peninsula Landfill (CPL),AK,Soldotna Landfill; Central Peninsula Baling Fa...,46915 Sterling Highway,Soldotna,Kenai Peninsula,99669,60.443004,...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,2010-Passive venting.,Alaska
4,1004380.0,11020,Merrill Field Landfill,AK,NaN,800 Merrill Field Drive,Anchorage,Anchorage,99501,61.212660,...,Yes,0.126,2021.0,33.2,Yes,1.0,0.126,2021.0,"2012-30 wells, system capacity=500 acfm.",Alaska
5,1011448.0,10980,Palmer Central Landfill,AK,Central Landfill - MatSu Borough,1201 N. 49th State Street\nJust off the Palmer...,Palmer,Matanuska-Susitna,99645,61.590000,...,Yes,0.174,2021.0,37.3,Yes,NaN,0.174,2021.0,NaN,Alaska
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2631,1011229.0,20722,Campbell County Landfill No.2,WY,NaN,4 North Landfill Road,Gillette,Campbell,82716,44.392560,...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,Wyoming
2632,1005225.0,11100,Casper Balefill,WY,City of Casper Regional Solid Waste Facility,1886 N. Station Road,Evansville,Natrona,82636,42.873192,...,Yes,0.287,2021.0,29.2,Yes,NaN,0.287,2021.0,2012-Passive vents/flares only.,Wyoming
2633,1005583.0,2196,Cheyenne Landfill,WY,NaN,1461 Happy Jack Road,Cheyenne,Laramie,82009,41.135000,...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,2012-Passive vents/flares only.,Wyoming
2634,1013159.0,21136,Eastern Laramie County SWDD,WY,NaN,4990 CR 216,Burns,Laramie,82053,41.230852,...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,Wyoming
2635,NaN,11140,Sheridan Existing Landfill,WY,NaN,83 East Ridge Road,Sheridan,Sheridan,82801,44.804335,...,No,NaN,NaN,NaN,No,NaN,NaN,NaN,1/09-Passive vents just installed.,Wyoming

In [98]:
landfill_sites_1990=landfill_sites_1990.groupby(["STATE","County"]).agg({"Landfill Name": "count"}).reset_index(drop=False)

In [99]:
landfill_sites_1990

          STATE    County  Landfill Name
0       Alabama    Blount              1
1       Alabama   Calhoun              1
2       Alabama   Colbert              1
3       Alabama   Cullman              1
4       Alabama   Houston              1
...         ...       ...            ...
1267  Wisconsin      Wood              2
1268    Wyoming  Campbell              1
1269    Wyoming   Laramie              2
1270    Wyoming   Natrona              1
1271    Wyoming  Sheridan              1

[1272 rows x 3 columns]

In [100]:
landfill_sites_1990.merge(county_list, left_on=["STATE","County"],right_on=["STATE","ALLCOUNTIES"])

,STATE,County,Landfill Name,GISJOIN,STATEICP,STATEFIPS,COUNTYFIPS,ALLCOUNTIES,VARIABLE NAME
0,Alabama,Blount,1,G0100090,41.0,1,90,Blount,NaN
1,Alabama,Calhoun,1,G0100150,41.0,1,150,Calhoun,NaN
2,Alabama,Colbert,1,G0100330,41.0,1,330,Colbert,NaN
3,Alabama,Cullman,1,G0100430,41.0,1,430,Cullman,NaN
4,Alabama,Houston,1,G0100690,41.0,1,690,Houston,NaN
...,...,...,...,...,...,...,...,...,...
1207,Wisconsin,Wood,2,G5500250,25.0,55,1410,Wood,NaN
1208,Wyoming,Campbell,1,G5500310,68.0,56,50,Campbell,NaN
1209,Wyoming,Laramie,2,G5500470,68.0,56,210,Laramie,NaN
1210,Wyoming,Natrona,1,G5500510,68.0,56,250,Natrona,NaN
1211,Wyoming,Sheridan,1,G5500590,68.0,56,330,Sheridan,NaN

In [101]:
census_1990_processed = pd.read_csv(r"..\..\Local\1990-census-processed.csv")
census_1990_processed

,Unnamed: 0,STATE,GISJOIN,STATEICP,STATEFIPS,COUNTYFIPS,ALLCOUNTIES,VARIABLE NAME,minority_county
0,0,Alabama,G0100010,41.0,1,10,Autauga,NaN,1
1,1,Alabama,G0100030,41.0,1,30,Baldwin,NaN,1
2,2,Alabama,G0100050,41.0,1,50,Barbour,NaN,1
3,3,Alabama,G0100070,41.0,1,70,Bibb,NaN,1
4,4,Alabama,G0100090,41.0,1,90,Blount,NaN,0
...,...,...,...,...,...,...,...,...,...
3253,3253,Wyoming,G5500650,68.0,56,390,Teton,NaN,0
3254,3254,Wyoming,G5500670,68.0,56,410,Uinta,NaN,0
3255,3255,Wyoming,G5500690,68.0,56,430,Washakie,NaN,0
3256,3256,Wyoming,G5500710,68.0,56,450,Weston,NaN,0
3257,3257,Wyoming,G5500730,68.0,56,470,Yellowstone National Park,NaN,0

In [102]:
landfill_sites_1990

          STATE    County  Landfill Name
0       Alabama    Blount              1
1       Alabama   Calhoun              1
2       Alabama   Colbert              1
3       Alabama   Cullman              1
4       Alabama   Houston              1
...         ...       ...            ...
1267  Wisconsin      Wood              2
1268    Wyoming  Campbell              1
1269    Wyoming   Laramie              2
1270    Wyoming   Natrona              1
1271    Wyoming  Sheridan              1

[1272 rows x 3 columns]

In [103]:
landfill_sites_1990["county_transformed"] = landfill_sites_1990["County"].apply(lambda x: county_name_transformer(x,["county","census" ,"area" ,"borough" ,"parish","municipality"]))
census_1990_processed["county_transformed"] = census_1990_processed["ALLCOUNTIES"].apply(lambda x: county_name_transformer(x,["county","census" ,"area" ,"borough" ,"parish","municipality"]))

In [104]:
temp = landfill_sites_1990.merge(census_1990_processed,left_on=["STATE","county_transformed"],right_on=["STATE","county_transformed"],how="left")
print(temp.shape)
temp[temp["minority_county"].isna()].count()

(1272, 12)

STATE                 30
County                30
Landfill Name         30
county_transformed    30
Unnamed: 0             0
GISJOIN                0
STATEICP               0
STATEFIPS              0
COUNTYFIPS             0
ALLCOUNTIES            0
VARIABLE NAME          0
minority_county        0
dtype: int64

In [105]:
temp=temp[["STATEFIPS","COUNTYFIPS","ALLCOUNTIES","minority_county","County"]]

In [106]:
labeled = county_list.merge(temp, on=["STATEFIPS","COUNTYFIPS","ALLCOUNTIES"],how="left")
3258-np.sum(labeled.isna())

STATE              3258
GISJOIN            3258
STATEICP           3166
STATEFIPS          3258
COUNTYFIPS         3258
ALLCOUNTIES        3258
VARIABLE NAME         0
minority_county    1242
County             1242
dtype: int64

In [107]:
labeled["label"]=(labeled["County"] != None) & (labeled["minority_county"] != None) & (labeled["minority_county"] == 1.0)
labeled["label"]=labeled["label"].astype("Int64")

In [123]:
labeled=labeled.drop(columns=["County","minority_county"])

In [124]:
labeled.head(5)

,STATE,GISJOIN,STATEICP,STATEFIPS,COUNTYFIPS,ALLCOUNTIES,VARIABLE NAME,label
0,Alabama,G0100010,41.0,1,10,Autauga,NaN,0
1,Alabama,G0100030,41.0,1,30,Baldwin,NaN,0
2,Alabama,G0100050,41.0,1,50,Barbour,NaN,0
3,Alabama,G0100070,41.0,1,70,Bibb,NaN,0
4,Alabama,G0100090,41.0,1,90,Blount,NaN,0

In [126]:
labeled[labeled["ALLCOUNTIES"]=="Jefferson"]

,STATE,GISJOIN,STATEICP,STATEFIPS,COUNTYFIPS,ALLCOUNTIES,VARIABLE NAME,label
36,Alabama,G0100730,41.0,1,730,Jefferson,NaN,1
168,Arkansas,G0202310,42.0,5,690,Jefferson,NaN,1
297,Colorado,G0600590,62.0,8,590,Jefferson,NaN,0
375,Florida,G0800990,43.0,12,650,Jefferson,NaN,0
491,Georgia,G1300450,44.0,13,1630,Jefferson,NaN,0
601,Idaho,G1302650,63.0,16,510,Jefferson,NaN,0
661,Illinois,G1600530,21.0,17,810,Jefferson,NaN,0
761,Indiana,G1701630,22.0,18,770,Jefferson,NaN,0
865,Iowa,G1801670,31.0,19,1010,Jefferson,NaN,0
957,Kansas,G1901670,32.0,20,870,Jefferson,NaN,0
1074,Kentucky,G2002030,51.0,21,1110,Jefferson,NaN,1
1164,Louisiana,G2101730,45.0,22,510,Jefferson,NaN,1
1458,Mississippi,G2701190,46.0,28,630,Jefferson,NaN,0
1558,Missouri,G2801450,34.0,29,990,Jefferson,NaN,0
1645,Montana,G2901550,64.0,30,430,Jefferson,NaN,0
1728,Nebraska,G3000910,35.0,31,950,Jefferson,NaN,0
1878,New York,G3400350,13.0,36,450,Jefferson,NaN,0
2111,Ohio,G3800690,24.0,39,810,Jefferson,NaN,0
2192,Oklahoma,G3901250,53.0,40,670,Jefferson,NaN,0
2251,Oregon,G4000670,72.0,41,310,Jefferson,NaN,0
2304,Pennsylvania,G4100190,14.0,42,650,Jefferson,NaN,0
2582,Tennessee,G4601090,54.0,47,890,Jefferson,NaN,0
2755,Texas,G4801270,49.0,48,2450,Jefferson,NaN,1
3083,Washington,G5101430,73.0,53,310,Jefferson,NaN,0
3125,West Virginia,G5101990,56.0,54,370,Jefferson,NaN,0
3189,Wisconsin,G5400470,25.0,55,550,Jefferson,NaN,0

In [122]:
np.sum(labeled["label"])

367